"""Initial Migration

Revision ID: f1493fffe7
Revises: None
Create Date: 2015-01-02 12:29:37.976008

"""

# revision identifiers, used by Alembic.
revision = 'f1493fffe7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('map', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_email'), 'jobs', ['email'], unique=False)
    op.create_index(op.f('ix_jobs_uid'), 'jobs', ['uid'], unique=True)
    op.create_table('residues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('res_type', sa.String(), nullable=True),
    sa.Column('res_id', sa.String(), nullable=True),
    sa.Column('chain_id', sa.String(), nullable=True),
    sa.Column('peak_angle', sa.Integer(), nullable=True),
    sa.Column('peak_density', sa.Float(), nullable=True),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_residues_chain_id'), 'residues', ['chain_id'], unique=False)
    op.create_index(op.f('ix_residues_job_id'), 'residues', ['job_id'], unique=False)
    op.create_index(op.f('ix_residues_peak_angle'), 'residues', ['peak_angle'], unique=False)
    op.create_index(op.f('ix_residues_peak_density'), 'residues', ['peak_density'], unique=False)
    op.create_index(op.f('ix_residues_res_id'), 'residues', ['res_id'], unique=False)
    op.create_index(op.f('ix_residues_res_type'), 'residues', ['res_type'], unique=False)
    op.create_table('angles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('angle', sa.Integer(), nullable=True),
    sa.Column('density', sa.Integer(), nullable=True),
    sa.Column('residue_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['residue_id'], ['residues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_angles_residue_id'), 'angles', ['residue_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_angles_residue_id'), table_name='angles')
    op.drop_table('angles')
    op.drop_index(op.f('ix_residues_res_type'), table_name='residues')
    op.drop_index(op.f('ix_residues_res_id'), table_name='residues')
    op.drop_index(op.f('ix_residues_peak_density'), table_name='residues')
    op.drop_index(op.f('ix_residues_peak_angle'), table_name='residues')
    op.drop_index(op.f('ix_residues_job_id'), table_name='residues')
    op.drop_index(op.f('ix_residues_chain_id'), table_name='residues')
    op.drop_table('residues')
    op.drop_index(op.f('ix_jobs_uid'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_email'), table_name='jobs')
    op.drop_table('jobs')
    ### end Alembic commands ###
